
# The name of your website.
name: collective edibles
title: food

description:

  # Description of your site. This will show up in google.
  meta: Collective Edibles is a site dedicated to the discussion of food, from production to consumption.

  # Description of your site. This will show up on the front page.
  subtitle: hi there! this website is undergoing maintenance, please feel free to have a browse but check back later for more juicy knowledge and recipes 👩🏽‍🍳
  name: Emily Whyman # Change this!

  # Necessary for contact page
  email: emily.whyman@iaac.net # Change this!

  # Optional text (html) to display after author name. Leave empty if you don't
  # want it.
  info:

url: www.collective-edibles.eu
# baseurl: /

# language attribute in <html> element.
lang: en

# FROM THIS POINT ON EVERYTHING IS OPTIONAL

##############
# APPEREANCE #
##############

# If you want to show the subtitle anywhere else than the front page, use
# {% include subtitle.html %} to include it anywhere you want.
show-subtitle: true
display-social-icons: false
# If you want social links to open in a new tab, set this as true
social-icons-open-newtab: false

footer-text: this is the bottom of the page

# Preferably 64px in height. Leave empty = disable.
logo-image: /img/logo.svg

# Toolbar color for Chrome on Android.
theme-color-attr: "#00f0ff"

# Color of Microsoft live Tile.
ms-tile-color: "#00f0ff"

# Color used throughout the theme. Format: R, G, B.
theme-color: 0, 240, 255 # Original: 0, 240, 255

# Text color used throughout the theme. Format: R, G, B.
text-color: 0, 0, 0 # Original: 0, 0, 0

# Background color used throughout the theme. Format: R, G, B.
# Note: if you change the background color AND you use cover images, you should
#       also change the CSS gradient in "_includes\gradient.css" to match the
#       background color. Edit and copy it from here:
#       http://www.colorzilla.com/gradient-editor/#ffffff+0,ffffff+100&0+0,1+100
background-color: 255, 255, 255 # Original: 255, 255, 255

display-author-post-page: true
display-author-front-page: true

# http://alanwsmith.com/jekyll-liquid-date-formatting-examples
date_format: "%b %-d, %Y"

# Minimal screen-width after which the navigation will change position from
# vertical to horizontal.
nav-breaking-point: 520px

# Number of posts on each page.
paginate: 3

# Display links for the previous and next post on post pages.
display-next-prev-post: false

# Leave empty if you don't want comments on post pages.
disqus-shortname:


################
# SOCIAL ICONS #
################

# Use a complete url here, including http:// and such. Requiring just usernames
# has been considered, but this is way more customizable.
twitter:
youtube:
instagram: https://www.instagram.com/collective_edibles/
tumblr:
facebook:
google-plus:
reddit:
soundcloud:
medium:
linkedin:
github:
behance:
codepen:
dribbble:
trello:
stack-overflow:
bitcoin:
paypal:


#####################
# CUSTOMIZABLE TEXT #
#####################

# Useful for translating into other languages.

var_on_the_web: on the web
var_read: read # Text after each post summary on the homepage.
var_newer: newer
var_older: older
var_next_post: next post
var_previous_post: previous post
var_less_than_a_minute_read: less than a minute read
var_min_read: min read # Text after reading time. Example: 5 min read.
var_post_by: post by
var_guest_post_by: guest post by
var_your_email: your email
var_your_message: your message


##################
# BUILD SETTINGS #
##################

# You don't have to change these.

exclude: [vendor]
highlighter: rouge
kramdown:
  input: GFM
paginate_path: "/page-:num/"
permalink: pretty
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: "<!--more-->"
      gems: ['jekyll-github-metadata']
      gems: ['jekyll-relative-links']
